default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: summa_user
  password: admin
  host: localhost

development:
  <<: *default
  database: summa_development

test:
  <<: *default
  database: summa_test

